before_script:
  - "bundle exec rake refinery:testing:dummy_app"
script: "bundle exec rake spec"
notifications:
  email:
    - parndt@gmail.com
    - ugis.ozolss@gmail.com
    - joe@joesak.com
    - jamie@enmasse.com
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite3
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - rbx-2.0
  - ree
  - jruby
