<%
ENV["RAILS_ENV"] ||= "test"
require ::File.expand_path('../spec/dummy/config/environment',  __FILE__)
rerun = IO.read('rerun.txt') if File.file?('rerun.txt')
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip -r features"
%>
default: <%= std_opts %>
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip